// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: nova/v1/nova.proto

package novapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inline HCL configuration content (not a file path, for isolation).
	HclConfig string `protobuf:"bytes,1,opt,name=hcl_config,json=hclConfig,proto3" json:"hcl_config,omitempty"`
	// Optional path to a user cloud-config.yaml.
	CloudConfigPath string `protobuf:"bytes,2,opt,name=cloud_config_path,json=cloudConfigPath,proto3" json:"cloud_config_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetHclConfig() string {
	if x != nil {
		return x.HclConfig
	}
	return ""
}

func (x *ApplyRequest) GetCloudConfigPath() string {
	if x != nil {
		return x.CloudConfigPath
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                                                                                                     // Detected OS family (e.g. "ubuntu", "alpine").
	PortForwards  map[int32]int32        `protobuf:"bytes,5,rep,name=port_forwards,json=portForwards,proto3" json:"port_forwards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // host_port -> guest_port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_nova_v1_nova_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeInfo) GetPortForwards() map[int32]int32 {
	if x != nil {
		return x.PortForwards
	}
	return nil
}

type DestroyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If empty, destroy all nodes. If set, destroy only this node.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Force-kill rather than graceful stop.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DestroyRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{4}
}

func (x *NodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatusResponse) Reset() {
	*x = NodeStatusResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatusResponse) ProtoMessage() {}

func (x *NodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatusResponse.ProtoReflect.Descriptor instead.
func (*NodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{5}
}

func (x *NodeStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeStatusResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeStatusResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *NodeStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeStatusResponse  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetNodes() []*NodeStatusResponse {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type LinkDegradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeA         string                 `protobuf:"bytes,1,opt,name=node_a,json=nodeA,proto3" json:"node_a,omitempty"`
	NodeB         string                 `protobuf:"bytes,2,opt,name=node_b,json=nodeB,proto3" json:"node_b,omitempty"`
	Latency       *durationpb.Duration   `protobuf:"bytes,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Jitter        *durationpb.Duration   `protobuf:"bytes,4,opt,name=jitter,proto3" json:"jitter,omitempty"`
	Loss          float64                `protobuf:"fixed64,5,opt,name=loss,proto3" json:"loss,omitempty"` // 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkDegradeRequest) Reset() {
	*x = LinkDegradeRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkDegradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkDegradeRequest) ProtoMessage() {}

func (x *LinkDegradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkDegradeRequest.ProtoReflect.Descriptor instead.
func (*LinkDegradeRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{7}
}

func (x *LinkDegradeRequest) GetNodeA() string {
	if x != nil {
		return x.NodeA
	}
	return ""
}

func (x *LinkDegradeRequest) GetNodeB() string {
	if x != nil {
		return x.NodeB
	}
	return ""
}

func (x *LinkDegradeRequest) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *LinkDegradeRequest) GetJitter() *durationpb.Duration {
	if x != nil {
		return x.Jitter
	}
	return nil
}

func (x *LinkDegradeRequest) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

type LinkPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeA         string                 `protobuf:"bytes,1,opt,name=node_a,json=nodeA,proto3" json:"node_a,omitempty"`
	NodeB         string                 `protobuf:"bytes,2,opt,name=node_b,json=nodeB,proto3" json:"node_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkPairRequest) Reset() {
	*x = LinkPairRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkPairRequest) ProtoMessage() {}

func (x *LinkPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkPairRequest.ProtoReflect.Descriptor instead.
func (*LinkPairRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{8}
}

func (x *LinkPairRequest) GetNodeA() string {
	if x != nil {
		return x.NodeA
	}
	return ""
}

func (x *LinkPairRequest) GetNodeB() string {
	if x != nil {
		return x.NodeB
	}
	return ""
}

type LinkStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conditions    []*LinkCondition       `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatusResponse) Reset() {
	*x = LinkStatusResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatusResponse) ProtoMessage() {}

func (x *LinkStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatusResponse.ProtoReflect.Descriptor instead.
func (*LinkStatusResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{9}
}

func (x *LinkStatusResponse) GetConditions() []*LinkCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type LinkCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeA         string                 `protobuf:"bytes,1,opt,name=node_a,json=nodeA,proto3" json:"node_a,omitempty"`
	NodeB         string                 `protobuf:"bytes,2,opt,name=node_b,json=nodeB,proto3" json:"node_b,omitempty"`
	Latency       *durationpb.Duration   `protobuf:"bytes,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Jitter        *durationpb.Duration   `protobuf:"bytes,4,opt,name=jitter,proto3" json:"jitter,omitempty"`
	Loss          float64                `protobuf:"fixed64,5,opt,name=loss,proto3" json:"loss,omitempty"`
	Partitioned   bool                   `protobuf:"varint,6,opt,name=partitioned,proto3" json:"partitioned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkCondition) Reset() {
	*x = LinkCondition{}
	mi := &file_nova_v1_nova_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkCondition) ProtoMessage() {}

func (x *LinkCondition) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkCondition.ProtoReflect.Descriptor instead.
func (*LinkCondition) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{10}
}

func (x *LinkCondition) GetNodeA() string {
	if x != nil {
		return x.NodeA
	}
	return ""
}

func (x *LinkCondition) GetNodeB() string {
	if x != nil {
		return x.NodeB
	}
	return ""
}

func (x *LinkCondition) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *LinkCondition) GetJitter() *durationpb.Duration {
	if x != nil {
		return x.Jitter
	}
	return nil
}

func (x *LinkCondition) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *LinkCondition) GetPartitioned() bool {
	if x != nil {
		return x.Partitioned
	}
	return false
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SnapshotListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotInfo        `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotListResponse) Reset() {
	*x = SnapshotListResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotListResponse) ProtoMessage() {}

func (x *SnapshotListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotListResponse.ProtoReflect.Descriptor instead.
func (*SnapshotListResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotListResponse) GetSnapshots() []*SnapshotInfo {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MachineCount  int32                  `protobuf:"varint,2,opt,name=machine_count,json=machineCount,proto3" json:"machine_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_nova_v1_nova_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SnapshotInfo) GetMachineCount() int32 {
	if x != nil {
		return x.MachineCount
	}
	return 0
}

func (x *SnapshotInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                           // VM/node name to export.
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                                       // Output format: "qcow2", "raw", "vmdk", "vhdx".
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`             // Destination file path.
	NoClean       bool                   `protobuf:"varint,4,opt,name=no_clean,json=noClean,proto3" json:"no_clean,omitempty"`                     // Skip sysprep.
	ZeroFreeSpace bool                   `protobuf:"varint,5,opt,name=zero_free_space,json=zeroFreeSpace,proto3" json:"zero_free_space,omitempty"` // Zero free space before export.
	SnapshotName  string                 `protobuf:"bytes,6,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`       // If set, take a pre-sysprep snapshot for rollback.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{14}
}

func (x *ExportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *ExportRequest) GetNoClean() bool {
	if x != nil {
		return x.NoClean
	}
	return false
}

func (x *ExportRequest) GetZeroFreeSpace() bool {
	if x != nil {
		return x.ZeroFreeSpace
	}
	return false
}

func (x *ExportRequest) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputPath    string                 `protobuf:"bytes,1,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{15}
}

func (x *ExportResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *ExportResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{16}
}

func (x *ExecRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_nova_v1_nova_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{17}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type WaitReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitReadyRequest) Reset() {
	*x = WaitReadyRequest{}
	mi := &file_nova_v1_nova_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitReadyRequest) ProtoMessage() {}

func (x *WaitReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitReadyRequest.ProtoReflect.Descriptor instead.
func (*WaitReadyRequest) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{18}
}

func (x *WaitReadyRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WaitReadyRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_nova_v1_nova_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{19}
}

func (x *LogEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *LogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ClusterEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event types: "node_starting", "node_running", "node_stopped",
	// "node_error", "link_degraded", "link_partitioned", "link_healed",
	// "snapshot_saved", "snapshot_restored"
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterEvent) Reset() {
	*x = ClusterEvent{}
	mi := &file_nova_v1_nova_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEvent) ProtoMessage() {}

func (x *ClusterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nova_v1_nova_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEvent.ProtoReflect.Descriptor instead.
func (*ClusterEvent) Descriptor() ([]byte, []int) {
	return file_nova_v1_nova_proto_rawDescGZIP(), []int{20}
}

func (x *ClusterEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClusterEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ClusterEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ClusterEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_nova_v1_nova_proto protoreflect.FileDescriptor

const file_nova_v1_nova_proto_rawDesc = "" +
	"\n" +
	"\x12nova/v1/nova.proto\x12\anova.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\fApplyRequest\x12\x1d\n" +
	"\n" +
	"hcl_config\x18\x01 \x01(\tR\thclConfig\x12*\n" +
	"\x11cloud_config_path\x18\x02 \x01(\tR\x0fcloudConfigPath\"8\n" +
	"\rApplyResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.nova.v1.NodeInfoR\x05nodes\"\xdf\x01\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12H\n" +
	"\rport_forwards\x18\x05 \x03(\v2#.nova.v1.NodeInfo.PortForwardsEntryR\fportForwards\x1a?\n" +
	"\x11PortForwardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\":\n" +
	"\x0eDestroyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"!\n" +
	"\vNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x99\x01\n" +
	"\x12NodeStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"C\n" +
	"\x0eStatusResponse\x121\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1b.nova.v1.NodeStatusResponseR\x05nodes\"\xbe\x01\n" +
	"\x12LinkDegradeRequest\x12\x15\n" +
	"\x06node_a\x18\x01 \x01(\tR\x05nodeA\x12\x15\n" +
	"\x06node_b\x18\x02 \x01(\tR\x05nodeB\x123\n" +
	"\alatency\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\alatency\x121\n" +
	"\x06jitter\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x06jitter\x12\x12\n" +
	"\x04loss\x18\x05 \x01(\x01R\x04loss\"?\n" +
	"\x0fLinkPairRequest\x12\x15\n" +
	"\x06node_a\x18\x01 \x01(\tR\x05nodeA\x12\x15\n" +
	"\x06node_b\x18\x02 \x01(\tR\x05nodeB\"L\n" +
	"\x12LinkStatusResponse\x126\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x16.nova.v1.LinkConditionR\n" +
	"conditions\"\xdb\x01\n" +
	"\rLinkCondition\x12\x15\n" +
	"\x06node_a\x18\x01 \x01(\tR\x05nodeA\x12\x15\n" +
	"\x06node_b\x18\x02 \x01(\tR\x05nodeB\x123\n" +
	"\alatency\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\alatency\x121\n" +
	"\x06jitter\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x06jitter\x12\x12\n" +
	"\x04loss\x18\x05 \x01(\x01R\x04loss\x12 \n" +
	"\vpartitioned\x18\x06 \x01(\bR\vpartitioned\"%\n" +
	"\x0fSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x14SnapshotListResponse\x123\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x15.nova.v1.SnapshotInfoR\tsnapshots\"\x82\x01\n" +
	"\fSnapshotInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rmachine_count\x18\x02 \x01(\x05R\fmachineCount\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc4\x01\n" +
	"\rExportRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\x12\x19\n" +
	"\bno_clean\x18\x04 \x01(\bR\anoClean\x12&\n" +
	"\x0fzero_free_space\x18\x05 \x01(\bR\rzeroFreeSpace\x12#\n" +
	"\rsnapshot_name\x18\x06 \x01(\tR\fsnapshotName\"h\n" +
	"\x0eExportResponse\x12\x1f\n" +
	"\voutput_path\x18\x01 \x01(\tR\n" +
	"outputPath\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"p\n" +
	"\vExecRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"[\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\"[\n" +
	"\x10WaitReadyRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"l\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x88\x01\n" +
	"\fClusterEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xe2\n" +
	"\n" +
	"\x04Nova\x126\n" +
	"\x05Apply\x12\x15.nova.v1.ApplyRequest\x1a\x16.nova.v1.ApplyResponse\x12:\n" +
	"\aDestroy\x12\x17.nova.v1.DestroyRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\bNodeStop\x12\x14.nova.v1.NodeRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\tNodeStart\x12\x14.nova.v1.NodeRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\bNodeKill\x12\x14.nova.v1.NodeRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\n" +
	"NodeStatus\x12\x14.nova.v1.NodeRequest\x1a\x1b.nova.v1.NodeStatusResponse\x129\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x17.nova.v1.StatusResponse\x12B\n" +
	"\vLinkDegrade\x12\x1b.nova.v1.LinkDegradeRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\rLinkPartition\x12\x18.nova.v1.LinkPairRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\bLinkHeal\x12\x18.nova.v1.LinkPairRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\tLinkReset\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"LinkStatus\x12\x16.google.protobuf.Empty\x1a\x1b.nova.v1.LinkStatusResponse\x129\n" +
	"\x06Export\x12\x16.nova.v1.ExportRequest\x1a\x17.nova.v1.ExportResponse\x12@\n" +
	"\fSnapshotSave\x12\x18.nova.v1.SnapshotRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\x0fSnapshotRestore\x12\x18.nova.v1.SnapshotRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fSnapshotList\x12\x16.google.protobuf.Empty\x1a\x1d.nova.v1.SnapshotListResponse\x12B\n" +
	"\x0eSnapshotDelete\x12\x18.nova.v1.SnapshotRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x04Exec\x12\x14.nova.v1.ExecRequest\x1a\x15.nova.v1.ExecResponse\x12>\n" +
	"\tWaitReady\x12\x19.nova.v1.WaitReadyRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\n" +
	"StreamLogs\x12\x14.nova.v1.NodeRequest\x1a\x11.nova.v1.LogEntry0\x01\x12?\n" +
	"\fStreamEvents\x12\x16.google.protobuf.Empty\x1a\x15.nova.v1.ClusterEvent0\x01\x12:\n" +
	"\bShutdown\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB#Z!github.com/3clabs/nova/pkg/novapbb\x06proto3"

var (
	file_nova_v1_nova_proto_rawDescOnce sync.Once
	file_nova_v1_nova_proto_rawDescData []byte
)

func file_nova_v1_nova_proto_rawDescGZIP() []byte {
	file_nova_v1_nova_proto_rawDescOnce.Do(func() {
		file_nova_v1_nova_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nova_v1_nova_proto_rawDesc), len(file_nova_v1_nova_proto_rawDesc)))
	})
	return file_nova_v1_nova_proto_rawDescData
}

var file_nova_v1_nova_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_nova_v1_nova_proto_goTypes = []any{
	(*ApplyRequest)(nil),          // 0: nova.v1.ApplyRequest
	(*ApplyResponse)(nil),         // 1: nova.v1.ApplyResponse
	(*NodeInfo)(nil),              // 2: nova.v1.NodeInfo
	(*DestroyRequest)(nil),        // 3: nova.v1.DestroyRequest
	(*NodeRequest)(nil),           // 4: nova.v1.NodeRequest
	(*NodeStatusResponse)(nil),    // 5: nova.v1.NodeStatusResponse
	(*StatusResponse)(nil),        // 6: nova.v1.StatusResponse
	(*LinkDegradeRequest)(nil),    // 7: nova.v1.LinkDegradeRequest
	(*LinkPairRequest)(nil),       // 8: nova.v1.LinkPairRequest
	(*LinkStatusResponse)(nil),    // 9: nova.v1.LinkStatusResponse
	(*LinkCondition)(nil),         // 10: nova.v1.LinkCondition
	(*SnapshotRequest)(nil),       // 11: nova.v1.SnapshotRequest
	(*SnapshotListResponse)(nil),  // 12: nova.v1.SnapshotListResponse
	(*SnapshotInfo)(nil),          // 13: nova.v1.SnapshotInfo
	(*ExportRequest)(nil),         // 14: nova.v1.ExportRequest
	(*ExportResponse)(nil),        // 15: nova.v1.ExportResponse
	(*ExecRequest)(nil),           // 16: nova.v1.ExecRequest
	(*ExecResponse)(nil),          // 17: nova.v1.ExecResponse
	(*WaitReadyRequest)(nil),      // 18: nova.v1.WaitReadyRequest
	(*LogEntry)(nil),              // 19: nova.v1.LogEntry
	(*ClusterEvent)(nil),          // 20: nova.v1.ClusterEvent
	nil,                           // 21: nova.v1.NodeInfo.PortForwardsEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 23: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 24: google.protobuf.Empty
}
var file_nova_v1_nova_proto_depIdxs = []int32{
	2,  // 0: nova.v1.ApplyResponse.nodes:type_name -> nova.v1.NodeInfo
	21, // 1: nova.v1.NodeInfo.port_forwards:type_name -> nova.v1.NodeInfo.PortForwardsEntry
	22, // 2: nova.v1.NodeStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	5,  // 3: nova.v1.StatusResponse.nodes:type_name -> nova.v1.NodeStatusResponse
	23, // 4: nova.v1.LinkDegradeRequest.latency:type_name -> google.protobuf.Duration
	23, // 5: nova.v1.LinkDegradeRequest.jitter:type_name -> google.protobuf.Duration
	10, // 6: nova.v1.LinkStatusResponse.conditions:type_name -> nova.v1.LinkCondition
	23, // 7: nova.v1.LinkCondition.latency:type_name -> google.protobuf.Duration
	23, // 8: nova.v1.LinkCondition.jitter:type_name -> google.protobuf.Duration
	13, // 9: nova.v1.SnapshotListResponse.snapshots:type_name -> nova.v1.SnapshotInfo
	22, // 10: nova.v1.SnapshotInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 11: nova.v1.ExecRequest.timeout:type_name -> google.protobuf.Duration
	23, // 12: nova.v1.WaitReadyRequest.timeout:type_name -> google.protobuf.Duration
	22, // 13: nova.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	22, // 14: nova.v1.ClusterEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 15: nova.v1.Nova.Apply:input_type -> nova.v1.ApplyRequest
	3,  // 16: nova.v1.Nova.Destroy:input_type -> nova.v1.DestroyRequest
	4,  // 17: nova.v1.Nova.NodeStop:input_type -> nova.v1.NodeRequest
	4,  // 18: nova.v1.Nova.NodeStart:input_type -> nova.v1.NodeRequest
	4,  // 19: nova.v1.Nova.NodeKill:input_type -> nova.v1.NodeRequest
	4,  // 20: nova.v1.Nova.NodeStatus:input_type -> nova.v1.NodeRequest
	24, // 21: nova.v1.Nova.Status:input_type -> google.protobuf.Empty
	7,  // 22: nova.v1.Nova.LinkDegrade:input_type -> nova.v1.LinkDegradeRequest
	8,  // 23: nova.v1.Nova.LinkPartition:input_type -> nova.v1.LinkPairRequest
	8,  // 24: nova.v1.Nova.LinkHeal:input_type -> nova.v1.LinkPairRequest
	24, // 25: nova.v1.Nova.LinkReset:input_type -> google.protobuf.Empty
	24, // 26: nova.v1.Nova.LinkStatus:input_type -> google.protobuf.Empty
	14, // 27: nova.v1.Nova.Export:input_type -> nova.v1.ExportRequest
	11, // 28: nova.v1.Nova.SnapshotSave:input_type -> nova.v1.SnapshotRequest
	11, // 29: nova.v1.Nova.SnapshotRestore:input_type -> nova.v1.SnapshotRequest
	24, // 30: nova.v1.Nova.SnapshotList:input_type -> google.protobuf.Empty
	11, // 31: nova.v1.Nova.SnapshotDelete:input_type -> nova.v1.SnapshotRequest
	16, // 32: nova.v1.Nova.Exec:input_type -> nova.v1.ExecRequest
	18, // 33: nova.v1.Nova.WaitReady:input_type -> nova.v1.WaitReadyRequest
	4,  // 34: nova.v1.Nova.StreamLogs:input_type -> nova.v1.NodeRequest
	24, // 35: nova.v1.Nova.StreamEvents:input_type -> google.protobuf.Empty
	24, // 36: nova.v1.Nova.Shutdown:input_type -> google.protobuf.Empty
	1,  // 37: nova.v1.Nova.Apply:output_type -> nova.v1.ApplyResponse
	24, // 38: nova.v1.Nova.Destroy:output_type -> google.protobuf.Empty
	24, // 39: nova.v1.Nova.NodeStop:output_type -> google.protobuf.Empty
	24, // 40: nova.v1.Nova.NodeStart:output_type -> google.protobuf.Empty
	24, // 41: nova.v1.Nova.NodeKill:output_type -> google.protobuf.Empty
	5,  // 42: nova.v1.Nova.NodeStatus:output_type -> nova.v1.NodeStatusResponse
	6,  // 43: nova.v1.Nova.Status:output_type -> nova.v1.StatusResponse
	24, // 44: nova.v1.Nova.LinkDegrade:output_type -> google.protobuf.Empty
	24, // 45: nova.v1.Nova.LinkPartition:output_type -> google.protobuf.Empty
	24, // 46: nova.v1.Nova.LinkHeal:output_type -> google.protobuf.Empty
	24, // 47: nova.v1.Nova.LinkReset:output_type -> google.protobuf.Empty
	9,  // 48: nova.v1.Nova.LinkStatus:output_type -> nova.v1.LinkStatusResponse
	15, // 49: nova.v1.Nova.Export:output_type -> nova.v1.ExportResponse
	24, // 50: nova.v1.Nova.SnapshotSave:output_type -> google.protobuf.Empty
	24, // 51: nova.v1.Nova.SnapshotRestore:output_type -> google.protobuf.Empty
	12, // 52: nova.v1.Nova.SnapshotList:output_type -> nova.v1.SnapshotListResponse
	24, // 53: nova.v1.Nova.SnapshotDelete:output_type -> google.protobuf.Empty
	17, // 54: nova.v1.Nova.Exec:output_type -> nova.v1.ExecResponse
	24, // 55: nova.v1.Nova.WaitReady:output_type -> google.protobuf.Empty
	19, // 56: nova.v1.Nova.StreamLogs:output_type -> nova.v1.LogEntry
	20, // 57: nova.v1.Nova.StreamEvents:output_type -> nova.v1.ClusterEvent
	24, // 58: nova.v1.Nova.Shutdown:output_type -> google.protobuf.Empty
	37, // [37:59] is the sub-list for method output_type
	15, // [15:37] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_nova_v1_nova_proto_init() }
func file_nova_v1_nova_proto_init() {
	if File_nova_v1_nova_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nova_v1_nova_proto_rawDesc), len(file_nova_v1_nova_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nova_v1_nova_proto_goTypes,
		DependencyIndexes: file_nova_v1_nova_proto_depIdxs,
		MessageInfos:      file_nova_v1_nova_proto_msgTypes,
	}.Build()
	File_nova_v1_nova_proto = out.File
	file_nova_v1_nova_proto_goTypes = nil
	file_nova_v1_nova_proto_depIdxs = nil
}
