// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: nova/v1/nova.proto

package novapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nova_Apply_FullMethodName           = "/nova.v1.Nova/Apply"
	Nova_Destroy_FullMethodName         = "/nova.v1.Nova/Destroy"
	Nova_NodeStop_FullMethodName        = "/nova.v1.Nova/NodeStop"
	Nova_NodeStart_FullMethodName       = "/nova.v1.Nova/NodeStart"
	Nova_NodeKill_FullMethodName        = "/nova.v1.Nova/NodeKill"
	Nova_NodeStatus_FullMethodName      = "/nova.v1.Nova/NodeStatus"
	Nova_Status_FullMethodName          = "/nova.v1.Nova/Status"
	Nova_LinkDegrade_FullMethodName     = "/nova.v1.Nova/LinkDegrade"
	Nova_LinkPartition_FullMethodName   = "/nova.v1.Nova/LinkPartition"
	Nova_LinkHeal_FullMethodName        = "/nova.v1.Nova/LinkHeal"
	Nova_LinkReset_FullMethodName       = "/nova.v1.Nova/LinkReset"
	Nova_LinkStatus_FullMethodName      = "/nova.v1.Nova/LinkStatus"
	Nova_Export_FullMethodName          = "/nova.v1.Nova/Export"
	Nova_SnapshotSave_FullMethodName    = "/nova.v1.Nova/SnapshotSave"
	Nova_SnapshotRestore_FullMethodName = "/nova.v1.Nova/SnapshotRestore"
	Nova_SnapshotList_FullMethodName    = "/nova.v1.Nova/SnapshotList"
	Nova_SnapshotDelete_FullMethodName  = "/nova.v1.Nova/SnapshotDelete"
	Nova_Exec_FullMethodName            = "/nova.v1.Nova/Exec"
	Nova_WaitReady_FullMethodName       = "/nova.v1.Nova/WaitReady"
	Nova_StreamLogs_FullMethodName      = "/nova.v1.Nova/StreamLogs"
	Nova_StreamEvents_FullMethodName    = "/nova.v1.Nova/StreamEvents"
	Nova_Shutdown_FullMethodName        = "/nova.v1.Nova/Shutdown"
)

// NovaClient is the client API for Nova service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NovaClient interface {
	// Apply boots all nodes defined in the provided HCL configuration.
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Destroy tears down all (or a specific) node and cleans up state.
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// NodeStop gracefully stops a single node.
	NodeStop(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// NodeStart starts a previously stopped node.
	NodeStart(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// NodeKill force-terminates a node (simulates power failure).
	// State is preserved but marked as error.
	NodeKill(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// NodeStatus returns the current state of a single node.
	NodeStatus(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeStatusResponse, error)
	// Status returns the state of all managed nodes.
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	// LinkDegrade sets latency, jitter, and/or packet loss between two nodes.
	LinkDegrade(ctx context.Context, in *LinkDegradeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// LinkPartition creates a hard network partition between two nodes.
	LinkPartition(ctx context.Context, in *LinkPairRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// LinkHeal removes all network conditions between two nodes.
	LinkHeal(ctx context.Context, in *LinkPairRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// LinkReset removes all network conditions across the cluster.
	LinkReset(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// LinkStatus returns all active network conditions.
	LinkStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LinkStatusResponse, error)
	// Export syspreps, shuts down, and exports a VM disk as a standalone image.
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// SnapshotSave saves a named snapshot of all nodes.
	SnapshotSave(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SnapshotRestore reverts all nodes to a saved snapshot.
	SnapshotRestore(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SnapshotList returns all saved snapshots.
	SnapshotList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SnapshotListResponse, error)
	// SnapshotDelete removes a saved snapshot.
	SnapshotDelete(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Exec runs a command on a node via SSH and returns the result.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// WaitReady blocks until a node is reachable via SSH (or timeout).
	WaitReady(ctx context.Context, in *WaitReadyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// StreamLogs streams serial console output from a node.
	StreamLogs(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// StreamEvents streams cluster-wide events (state changes, chaos, etc).
	StreamEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterEvent], error)
	// Shutdown gracefully shuts down the daemon, stopping all VMs first.
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type novaClient struct {
	cc grpc.ClientConnInterface
}

func NewNovaClient(cc grpc.ClientConnInterface) NovaClient {
	return &novaClient{cc}
}

func (c *novaClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, Nova_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) NodeStop(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_NodeStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) NodeStart(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_NodeStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) NodeKill(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_NodeKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) NodeStatus(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatusResponse)
	err := c.cc.Invoke(ctx, Nova_NodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Nova_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) LinkDegrade(ctx context.Context, in *LinkDegradeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_LinkDegrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) LinkPartition(ctx context.Context, in *LinkPairRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_LinkPartition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) LinkHeal(ctx context.Context, in *LinkPairRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_LinkHeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) LinkReset(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_LinkReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) LinkStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*LinkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkStatusResponse)
	err := c.cc.Invoke(ctx, Nova_LinkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, Nova_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) SnapshotSave(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_SnapshotSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) SnapshotRestore(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_SnapshotRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) SnapshotList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotListResponse)
	err := c.cc.Invoke(ctx, Nova_SnapshotList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) SnapshotDelete(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_SnapshotDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, Nova_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) WaitReady(ctx context.Context, in *WaitReadyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_WaitReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaClient) StreamLogs(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nova_ServiceDesc.Streams[0], Nova_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nova_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *novaClient) StreamEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nova_ServiceDesc.Streams[1], Nova_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ClusterEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nova_StreamEventsClient = grpc.ServerStreamingClient[ClusterEvent]

func (c *novaClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Nova_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NovaServer is the server API for Nova service.
// All implementations must embed UnimplementedNovaServer
// for forward compatibility.
type NovaServer interface {
	// Apply boots all nodes defined in the provided HCL configuration.
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	// Destroy tears down all (or a specific) node and cleans up state.
	Destroy(context.Context, *DestroyRequest) (*emptypb.Empty, error)
	// NodeStop gracefully stops a single node.
	NodeStop(context.Context, *NodeRequest) (*emptypb.Empty, error)
	// NodeStart starts a previously stopped node.
	NodeStart(context.Context, *NodeRequest) (*emptypb.Empty, error)
	// NodeKill force-terminates a node (simulates power failure).
	// State is preserved but marked as error.
	NodeKill(context.Context, *NodeRequest) (*emptypb.Empty, error)
	// NodeStatus returns the current state of a single node.
	NodeStatus(context.Context, *NodeRequest) (*NodeStatusResponse, error)
	// Status returns the state of all managed nodes.
	Status(context.Context, *emptypb.Empty) (*StatusResponse, error)
	// LinkDegrade sets latency, jitter, and/or packet loss between two nodes.
	LinkDegrade(context.Context, *LinkDegradeRequest) (*emptypb.Empty, error)
	// LinkPartition creates a hard network partition between two nodes.
	LinkPartition(context.Context, *LinkPairRequest) (*emptypb.Empty, error)
	// LinkHeal removes all network conditions between two nodes.
	LinkHeal(context.Context, *LinkPairRequest) (*emptypb.Empty, error)
	// LinkReset removes all network conditions across the cluster.
	LinkReset(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// LinkStatus returns all active network conditions.
	LinkStatus(context.Context, *emptypb.Empty) (*LinkStatusResponse, error)
	// Export syspreps, shuts down, and exports a VM disk as a standalone image.
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	// SnapshotSave saves a named snapshot of all nodes.
	SnapshotSave(context.Context, *SnapshotRequest) (*emptypb.Empty, error)
	// SnapshotRestore reverts all nodes to a saved snapshot.
	SnapshotRestore(context.Context, *SnapshotRequest) (*emptypb.Empty, error)
	// SnapshotList returns all saved snapshots.
	SnapshotList(context.Context, *emptypb.Empty) (*SnapshotListResponse, error)
	// SnapshotDelete removes a saved snapshot.
	SnapshotDelete(context.Context, *SnapshotRequest) (*emptypb.Empty, error)
	// Exec runs a command on a node via SSH and returns the result.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// WaitReady blocks until a node is reachable via SSH (or timeout).
	WaitReady(context.Context, *WaitReadyRequest) (*emptypb.Empty, error)
	// StreamLogs streams serial console output from a node.
	StreamLogs(*NodeRequest, grpc.ServerStreamingServer[LogEntry]) error
	// StreamEvents streams cluster-wide events (state changes, chaos, etc).
	StreamEvents(*emptypb.Empty, grpc.ServerStreamingServer[ClusterEvent]) error
	// Shutdown gracefully shuts down the daemon, stopping all VMs first.
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedNovaServer()
}

// UnimplementedNovaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNovaServer struct{}

func (UnimplementedNovaServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedNovaServer) Destroy(context.Context, *DestroyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedNovaServer) NodeStop(context.Context, *NodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStop not implemented")
}
func (UnimplementedNovaServer) NodeStart(context.Context, *NodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStart not implemented")
}
func (UnimplementedNovaServer) NodeKill(context.Context, *NodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeKill not implemented")
}
func (UnimplementedNovaServer) NodeStatus(context.Context, *NodeRequest) (*NodeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStatus not implemented")
}
func (UnimplementedNovaServer) Status(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedNovaServer) LinkDegrade(context.Context, *LinkDegradeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkDegrade not implemented")
}
func (UnimplementedNovaServer) LinkPartition(context.Context, *LinkPairRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkPartition not implemented")
}
func (UnimplementedNovaServer) LinkHeal(context.Context, *LinkPairRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkHeal not implemented")
}
func (UnimplementedNovaServer) LinkReset(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkReset not implemented")
}
func (UnimplementedNovaServer) LinkStatus(context.Context, *emptypb.Empty) (*LinkStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkStatus not implemented")
}
func (UnimplementedNovaServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedNovaServer) SnapshotSave(context.Context, *SnapshotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotSave not implemented")
}
func (UnimplementedNovaServer) SnapshotRestore(context.Context, *SnapshotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotRestore not implemented")
}
func (UnimplementedNovaServer) SnapshotList(context.Context, *emptypb.Empty) (*SnapshotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotList not implemented")
}
func (UnimplementedNovaServer) SnapshotDelete(context.Context, *SnapshotRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotDelete not implemented")
}
func (UnimplementedNovaServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedNovaServer) WaitReady(context.Context, *WaitReadyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitReady not implemented")
}
func (UnimplementedNovaServer) StreamLogs(*NodeRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedNovaServer) StreamEvents(*emptypb.Empty, grpc.ServerStreamingServer[ClusterEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedNovaServer) Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedNovaServer) mustEmbedUnimplementedNovaServer() {}
func (UnimplementedNovaServer) testEmbeddedByValue()              {}

// UnsafeNovaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NovaServer will
// result in compilation errors.
type UnsafeNovaServer interface {
	mustEmbedUnimplementedNovaServer()
}

func RegisterNovaServer(s grpc.ServiceRegistrar, srv NovaServer) {
	// If the following call panics, it indicates UnimplementedNovaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nova_ServiceDesc, srv)
}

func _Nova_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_NodeStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).NodeStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_NodeStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).NodeStop(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_NodeStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).NodeStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_NodeStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).NodeStart(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_NodeKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).NodeKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_NodeKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).NodeKill(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_NodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).NodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_NodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).NodeStatus(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_LinkDegrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkDegradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).LinkDegrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_LinkDegrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).LinkDegrade(ctx, req.(*LinkDegradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_LinkPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).LinkPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_LinkPartition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).LinkPartition(ctx, req.(*LinkPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_LinkHeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).LinkHeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_LinkHeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).LinkHeal(ctx, req.(*LinkPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_LinkReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).LinkReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_LinkReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).LinkReset(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_LinkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).LinkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_LinkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).LinkStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_SnapshotSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).SnapshotSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_SnapshotSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).SnapshotSave(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_SnapshotRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).SnapshotRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_SnapshotRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).SnapshotRestore(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_SnapshotList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).SnapshotList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_SnapshotList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).SnapshotList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_SnapshotDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).SnapshotDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_SnapshotDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).SnapshotDelete(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_WaitReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).WaitReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_WaitReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).WaitReady(ctx, req.(*WaitReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nova_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NovaServer).StreamLogs(m, &grpc.GenericServerStream[NodeRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nova_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _Nova_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NovaServer).StreamEvents(m, &grpc.GenericServerStream[emptypb.Empty, ClusterEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nova_StreamEventsServer = grpc.ServerStreamingServer[ClusterEvent]

func _Nova_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nova_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Nova_ServiceDesc is the grpc.ServiceDesc for Nova service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nova_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nova.v1.Nova",
	HandlerType: (*NovaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Nova_Apply_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Nova_Destroy_Handler,
		},
		{
			MethodName: "NodeStop",
			Handler:    _Nova_NodeStop_Handler,
		},
		{
			MethodName: "NodeStart",
			Handler:    _Nova_NodeStart_Handler,
		},
		{
			MethodName: "NodeKill",
			Handler:    _Nova_NodeKill_Handler,
		},
		{
			MethodName: "NodeStatus",
			Handler:    _Nova_NodeStatus_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Nova_Status_Handler,
		},
		{
			MethodName: "LinkDegrade",
			Handler:    _Nova_LinkDegrade_Handler,
		},
		{
			MethodName: "LinkPartition",
			Handler:    _Nova_LinkPartition_Handler,
		},
		{
			MethodName: "LinkHeal",
			Handler:    _Nova_LinkHeal_Handler,
		},
		{
			MethodName: "LinkReset",
			Handler:    _Nova_LinkReset_Handler,
		},
		{
			MethodName: "LinkStatus",
			Handler:    _Nova_LinkStatus_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Nova_Export_Handler,
		},
		{
			MethodName: "SnapshotSave",
			Handler:    _Nova_SnapshotSave_Handler,
		},
		{
			MethodName: "SnapshotRestore",
			Handler:    _Nova_SnapshotRestore_Handler,
		},
		{
			MethodName: "SnapshotList",
			Handler:    _Nova_SnapshotList_Handler,
		},
		{
			MethodName: "SnapshotDelete",
			Handler:    _Nova_SnapshotDelete_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _Nova_Exec_Handler,
		},
		{
			MethodName: "WaitReady",
			Handler:    _Nova_WaitReady_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Nova_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Nova_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _Nova_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nova/v1/nova.proto",
}
